CREATE TABLE IF NOT EXISTS faa_aircraft_registration_master (
  unique_id VARCHAR(8),
  n_number VARCHAR(5),
  mode_s_code INTEGER,
  mode_s_code_hex VARCHAR(10),
  serial_number VARCHAR(30),
  status_code VARCHAR(2),
  aircraft_combo_code VARCHAR(7),
  aircraft_type_code VARCHAR(1),
  engine_type_code INTEGER,
  engine_combo_code VARCHAR(5),
  kit_manufacturer_name VARCHAR(30),
  kit_manufacturer_model VARCHAR(20),
  year_manufactured VARCHAR(4),
  registrant_type_code INTEGER,
  registrant_name VARCHAR(50),
  registrant_address_line1 VARCHAR(33),
  registrant_address_line2 VARCHAR(33),
  registrant_city VARCHAR(18),
  registrant_state_code VARCHAR(2),
  registrant_region_code VARCHAR(1),
  registrant_county_code VARCHAR(3),
  registrant_postal_code VARCHAR(10),
  registrant_country_code VARCHAR(2),
  certification_code VARCHAR(10),
  fractional_owner VARCHAR(1),
  other_name1 VARCHAR(50),
  other_name2 VARCHAR(50),
  other_name3 VARCHAR(50),
  other_name4 VARCHAR(50),
  other_name5 VARCHAR(50),
  airworthiness_date DATE,
  cert_issue_date DATE,
  expiration_date DATE,
  last_action_date DATE
);

CREATE TABLE IF NOT EXISTS faa_aircraft_reference (
  combo_code VARCHAR(7),
  manufacturer_code VARCHAR(3),
  model_code VARCHAR(2),
  series_code VARCHAR(2),
  manufacturer_name VARCHAR(30),
  model_name VARCHAR(20),
  type_code VARCHAR(1),
  engine_type_code INTEGER,
  category_code INTEGER,
  builder_certification_code INTEGER,
  number_of_engines INTEGER,
  max_number_of_seats INTEGER,
  weight VARCHAR(7),
  cruising_speed_mph INTEGER
);

CREATE TABLE IF NOT EXISTS faa_engine_reference (
  combo_code VARCHAR(5),
  manufacturer_name VARCHAR(10),
  model_name VARCHAR(13),
  type_code INTEGER,
  horsepower INTEGER,
  thrust_lbs INTEGER
);

CREATE TABLE IF NOT EXISTS faa_reserved_n_numbers (
  n_number VARCHAR(5),
  registrant_name VARCHAR(50),
  registrant_address_line1 VARCHAR(33),
  registrant_address_line2 VARCHAR(33),
  registrant_city VARCHAR(18),
  registrant_state_code VARCHAR(2),
  registrant_postal_code VARCHAR(10),
  reserve_date DATE,
  reservation_type_code VARCHAR(2),
  expiration_notice_date DATE,
  changed_n_number VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS faa_aircraft_deregistered (
  n_number VARCHAR(5),
  mode_s_code INTEGER,
  mode_s_code_hex VARCHAR(10),
  serial_number VARCHAR(30),
  aircraft_combo_code VARCHAR(7),
  engine_combo_code VARCHAR(5),
  status_code VARCHAR(2),
  registrant_type_code INTEGER,
  registrant_name VARCHAR(50),
  registrant_address_line1 VARCHAR(33),
  registrant_address_line2 VARCHAR(33),
  registrant_city VARCHAR(18),
  registrant_region_code VARCHAR(1),
  registrant_county_code VARCHAR(3),
  registrant_state_code VARCHAR(2),
  registrant_postal_code VARCHAR(10),
  registrant_country_code VARCHAR(2),
  physical_address_line1 VARCHAR(33),
  physical_address_line2 VARCHAR(33),
  physical_city VARCHAR(18),
  physical_state_code VARCHAR(2),
  physical_county_code VARCHAR(3),
  physical_postal_code VARCHAR(10),
  physical_country_code VARCHAR(2),
  year_manufactured VARCHAR(4),
  certification_code VARCHAR(10),
  export_country VARCHAR(18),
  other_name1 VARCHAR(50),
  other_name2 VARCHAR(50),
  other_name3 VARCHAR(50),
  other_name4 VARCHAR(50),
  other_name5 VARCHAR(50),
  kit_manufacturer_name VARCHAR(30),
  kit_manufacturer_model VARCHAR(20),
  airworthiness_date DATE,
  cancel_date DATE,
  last_action_date DATE
);
