#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'ox'
require 'stringio'
require 'zlib'

if ARGV.size < 1
  puts "syntax: noaa_nws_awc_get_metars <path-to-json-output-file>"
  exit 1
end

JSON_FILE = ARGV[0]

SOURCE_URL = 'https://aviationweather.gov/data/cache/metars.cache.xml.gz'

uri = URI(SOURCE_URL)
res = Net::HTTP.get(uri)
gz = Zlib::GzipReader.new(StringIO.new(res))    
xml_data = gz.read
content = Ox.load(xml_data, mode: :hash)
info = content[:response][7][:data][0]
metars = content[:response][7][:data][1..-1].map do |i|
  metar = i[:METAR]
  metar[:sky_condition] = metar[:sky_condition] ? metar[:sky_condition].flatten : []
  metar
end

content = {
  source: {
    name: 'Airframes Project',
    url: 'https://github.com/airframesio',
    email: 'kevin@airframes.io'
  },
  attribution: {
    name: 'NOAA NWS Aviation Weather Center',
    url: SOURCE_URL
  },
  resource_type: 'metars',
  count: metars.size,
  metars: metars
}

File.open(JSON_FILE, 'w') do |f|
  f.write(JSON.pretty_generate(content))
end

puts "Retrieved #{metars.size} METARs and wrote to #{JSON_FILE}."
